[package]
name = "teamdeck-tracker-api"
version = "0.1.0"
edition = "2018"
authors = ["Arkadiusz Żmudzin <arkadiusz.zmudzin@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "teamdeck_tracker_api"

[dependencies]
async-graphql = "2.9.10"
async-graphql-actix-web = "2.9.10"
actix-web = "3"
chrono = "0.4.19"
reqwest = { version = "0.10.10", features = ["serde_json", "json"] }
serde = { version = "1", features = ["derive"]}
thiserror = "1.0.26"